/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *imen_bm_Gestion_des_centres;
  GtkWidget *imen_bm_Ajouter;
  GtkWidget *imen_bm_Modifier;
  GtkWidget *imen_bm_Supprimer;
  GtkWidget *imen_bm_Rechercher;
  GtkWidget *imen_bm_Inscription____un_centre;
  GtkWidget *imen_bm_Statistiques_Filtr__es;
  GtkWidget *imen_bm_message_1;
  GtkWidget *imen_bm_message_2;
  GtkWidget *imen_bm_message_3;
  GtkWidget *imen_bm_Error;
  GtkWidget *imen_bm_Message_de_confirmation;
  GtkWidget *imen_bm_Error_ajouter;
  GtkWidget *imen_bm_message_4;
  GtkWidget *imen_bm_message_5;
  GtkWidget *imen_bm_message_6;
  GtkWidget *imen_bm_message_7;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  imen_bm_Gestion_des_centres = create_imen_bm_Gestion_des_centres ();
  gtk_widget_show (imen_bm_Gestion_des_centres);
  imen_bm_Ajouter = create_imen_bm_Ajouter ();
 // gtk_widget_show (imen_bm_Ajouter);
  imen_bm_Modifier = create_imen_bm_Modifier ();
 // gtk_widget_show (imen_bm_Modifier);
  imen_bm_Supprimer = create_imen_bm_Supprimer ();
  //gtk_widget_show (imen_bm_Supprimer);
  imen_bm_Rechercher = create_imen_bm_Rechercher ();
  //gtk_widget_show (imen_bm_Rechercher);
  imen_bm_Inscription____un_centre = create_imen_bm_Inscription____un_centre ();
  //gtk_widget_show (imen_bm_Inscription____un_centre);
  imen_bm_Statistiques_Filtr__es = create_imen_bm_Statistiques_Filtr__es ();
  //gtk_widget_show (imen_bm_Statistiques_Filtr__es);
  imen_bm_message_1 = create_imen_bm_message_1 ();
  //gtk_widget_show (imen_bm_message_1);
  imen_bm_message_2 = create_imen_bm_message_2 ();
  //gtk_widget_show (imen_bm_message_2);
  imen_bm_message_3 = create_imen_bm_message_3 ();
  //gtk_widget_show (imen_bm_message_3);
  imen_bm_Error = create_imen_bm_Error ();
  //gtk_widget_show (imen_bm_Error);
  imen_bm_Message_de_confirmation = create_imen_bm_Message_de_confirmation ();
  //gtk_widget_show (imen_bm_Message_de_confirmation);
  imen_bm_Error_ajouter = create_imen_bm_Error_ajouter ();
  //gtk_widget_show (imen_bm_Error_ajouter);
  imen_bm_message_4 = create_imen_bm_message_4 ();
  //gtk_widget_show (imen_bm_message_4);
  imen_bm_message_5 = create_imen_bm_message_5 ();
  //gtk_widget_show (imen_bm_message_5);
  imen_bm_message_6 = create_imen_bm_message_6 ();
  //gtk_widget_show (imen_bm_message_6);
  imen_bm_message_7 = create_imen_bm_message_7 ();
  //gtk_widget_show (imen_bm_message_7);

  gtk_main ();
  return 0;
}

