/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_imen_bm_Gestion_des_centres (void);
GtkWidget* create_imen_bm_Ajouter (void);
GtkWidget* create_imen_bm_Modifier (void);
GtkWidget* create_imen_bm_Suppmod (void);
GtkWidget* create_imen_bm_Rechercher (void);
GtkWidget* create_imen_bm_Inscription____un_centre (void);
GtkWidget* create_imen_bm_Statistiques_Filtrees (void);
GtkWidget* create_imen_bm_Message_de_confirmation (void);
GtkWidget* create_Espace_Admin (void);
GtkWidget* create_Espace_Entraineur (void);
GtkWidget* create_Authentification (void);
